#!/usr/bin/env python3
"""Generate candidate offsets from a saved AccurateRip HTML table."""

import argparse
from collections import defaultdict
import gzip
import hashlib
from html.parser import HTMLParser
from pathlib import Path
import re


SOURCE_URL = 'https://www.accuraterip.com/driveoffsets.htm'


class DriveTableParser(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.rows = []
        self.row = []
        self.cell = None

    def handle_starttag(self, tag, attrs):
        if tag == 'tr':
            self.row = []
        elif tag in ('td', 'th'):
            self.cell = []

    def handle_data(self, data):
        if self.cell is not None:
            self.cell.append(data)

    def handle_endtag(self, tag):
        if tag in ('td', 'th') and self.cell is not None:
            self.row.append(' '.join(''.join(self.cell).split()))
            self.cell = None
        elif tag == 'tr' and self.row:
            self.rows.append(self.row)


def generate(source):
    """Return deterministic Python data; counts rank, never verify, offsets."""
    parser = DriveTableParser()
    # The published page is Windows-1252, including non-ASCII model names.
    parser.feed(source.decode('windows-1252'))
    entries = defaultdict(lambda: defaultdict(int))
    row_count = 0
    for row in parser.rows:
        if len(row) != 4 or not re.fullmatch(r'[+-]?\d+', row[1]):
            continue
        if not row[0] or not re.fullmatch(r'\d+', row[2]):
            raise ValueError('invalid drive row: {!r}'.format(row))
        name = ' '.join(row[0].upper().split())
        entries[name][int(row[1])] += int(row[2])
        row_count += 1
    if not entries:
        raise ValueError('no drive offsets found in input')
    lines = [
        '# Generated by misc/gen_drive_offsets.py; do not edit.',
        '# flake8: noqa',
        '# Published candidates, not independently verified drive offsets.',
        'SOURCE_URL = {!r}'.format(SOURCE_URL),
        'SOURCE_SHA256 = {!r}'.format(hashlib.sha256(source).hexdigest()),
        'SOURCE_ROWS = {}'.format(row_count),
        '',
        '# Full vendor/model name -> (offset in samples, submission count).',
        'MODEL_OFFSETS = {',
    ]
    for name, offsets in sorted(entries.items()):
        ranked = tuple(sorted(offsets.items(),
                              key=lambda item: (-item[1], item[0])))
        lines.append('    {!r}: {!r},'.format(name, ranked))
    lines.append('}\n')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input', type=Path, required=True,
                        help='saved AccurateRip driveoffsets.htm')
    parser.add_argument('--output', type=Path, required=True,
                        help='generated Python data module')
    args = parser.parse_args()
    source = args.input.read_bytes()
    if source.startswith(b'\x1f\x8b'):
        source = gzip.decompress(source)
    result = generate(source)
    args.output.write_text(result, encoding='utf-8')


if __name__ == '__main__':
    main()
